# Generated by Django 5.2.17 on 2026-09-25 01:50

import catalog.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240, verbose_name='título')),
                ('author', models.CharField(blank=True, max_length=180, verbose_name='autor')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='descripción')),
                ('pdf', models.FileField(upload_to=catalog.models.pdf_path, verbose_name='PDF')),
                ('cover', models.FileField(upload_to=catalog.models.cover_path, verbose_name='portada')),
                ('pages', models.PositiveIntegerField(verbose_name='páginas')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
